name: "Run test script after a PR to master"
run-name: "PR to master, triggered by ${{github.actor}}."

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['master']
jobs:
  my-run-tests-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 'Checkout project'
        uses: actions/checkout@v3
        
      - name: 'Setup NodeJs'
        uses: actions/setup-node@v3
        with:
          version: 18
        
      - name: 'Install dependencies'
        run: npm ci
        
      - name: 'Log test start'
        run: echo Running tests
        
      - name: 'Run tests'
        run: npm run test a
        
      - name: 'Log build start'
        run: echo Building project
      
      - name: 'Run build'
        run: npm run build
